extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["COTHON"].append_array(COTHON)

var COTHON = [
	{
			"weaponSlot":{
				"right":{
					"type":"SYSTEM_EMD14"
				}, 
				"left":{
					"type":"SYSTEM_NONE"
				}
			}, 
			"reactor":{
				"power":8.0
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0, 
			}, 
			"fuel":{
				"capacity":80000.0, 
				"initial":80000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":200.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"cargo":{
				"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_PNTR", 
				"rcs":"SYSTEM_THRUSTER_NDSTR"
			}, 
		},
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_MWG"
				}, 
			"left":{
				"type":"SYSTEM_MWG"
				}
			}, 
		"reactor":{
			"power":8.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":0.0, 
			"initial":0.0
			}, 
		"fuel":{
			"capacity":80000.0, 
			"initial":80000.0, 
			}, 
		"capacitor":{
			"capacity":1000.0, 
			}, 
		"turbine":{
			"power":200.0, 
			},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_PNTR", 
			"rcs":"SYSTEM_THRUSTER_NDSTR"
			}
		}, 
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_CL600P"
				}, 
			"left":{
				"type":"SYSTEM_CL600P"
				},
			"rightBack":{
				"type":"SYSTEM_EXSTORAGE-R"
				},
			"leftBack":{
				"type":"SYSTEM_EXSTORAGE-L"
				}
			}, 
		"reactor":{
			"power":30.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":0.0, 
			"initial":0.0
			}, 
		"fuel":{
			"capacity":80000.0, 
			"initial":80000.0, 
			}, 
		"capacitor":{
			"capacity":1500.0, 
			}, 
		"turbine":{
			"power":500.0, 
			}, 
		"aux":{
			"power":"SYSTEM_AUX_SMES_MK2"
			},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535", 
			"rcs":"SYSTEM_THRUSTER_MA150HO"
			}
		}, 
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_DND_HAUL"
				}, 
			"left":{
				"type":"SYSTEM_PDMWG-L"
				}
			}, 
		"reactor":{
			"power":20.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":5000.0, 
			"initial":5000.0
			}, 
		"fuel":{
			"capacity":50000.0, 
			"initial":50000.0, 
			}, 
		"capacitor":{
			"capacity":1000.0, 
			}, 
		"turbine":{
			"power":200.0, 
			},
		"shielding":{
			"emp":0, 
			}, 
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUFSO"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535", 
			"rcs":"SYSTEM_THRUSTER_MA150HO"
			}
		},
		{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_NONE"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GRAVIMETRIC"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":50000,
			"initial":50000
		},
		"hud":{
			"type":"SYSTEM_HUD_HAL"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535",
			"rcs":"SYSTEM_THRUSTER_NDVTT"
		},
		"reactor":{
			"power":12
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_HUNK-L"
			},
			"leftBack":{
				"type":"SYSTEM_HUNK-L"
			},
			"right":{
				"type":"SYSTEM_ACL200P"
			},
			"rightBack":{
				"type":"SYSTEM_DND_HAUL"
			}
		}
	},
		{
		"ammo":{
			"capacity":20000,
			"initial":20000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK4"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GUIDING"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_PROSPECTOR_BALD"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_OPA"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_DND_FIX"
			},
			"leftBack":{
				"type":"SYSTEM_DND_FIX"
			},
			"right":{
				"type":"SYSTEM_DND_FIX"
			},
			"rightBack":{
				"type":"SYSTEM_DND_FIX"
			}
		}
	},
		{
		"ammo":{
			"capacity":20000,
			"initial":20000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK2"
		},
		"aux":{
			"power":"SYSTEM_AUX_MPD_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_STANDARD"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_HAL"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_SCOOP-L"
			},
			"leftBack":{
				"type":"SYSTEM_EXSTORAGE-L"
			},
			"right":{
				"type":"SYSTEM_MWG"
			},
			"rightBack":{
				"type":"SYSTEM_EXSTORAGE-R"
			}
		}
	},
		{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK1"
		},
		"aux":{
			"power":"SYSTEM_NONE"
		},
		"capacitor":{
			"capacity":500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUFSO"
		},
		"drone":{
			"scanner":"SYSTEM_RD_STANDARD"
		},
		"drones":{
			"capacity":0,
			"initial":0
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_RADAR"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_NDNTR",
			"rcs":"SYSTEM_THRUSTER_MA150HO"
		},
		"reactor":{
			"power":8
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_SCOOP-L"
			},
			"leftBack":{
				"type":"SYSTEM_EXSTORAGE-L"
			},
			"right":{
				"type":"SYSTEM_MWG"
			},
			"rightBack":{
				"type":"SYSTEM_EXSTORAGE-R"
			}
		}
	}
]
