extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["EIME"] = EIME

var EIME = [
	{
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_AGILE"
			}, 
			"weaponSlot":{
				"main":{
					"type":"SYSTEM_NONE"
				}, 
				"left":{
					"type":"SYSTEM_NONE"
				}, 
				"right":{
					"type":"SYSTEM_NONE"
				}, 
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			}, 
			"capacitor":{
				"capacity":1000.0
			}, 
			"turbine":{
				"power":1000.0
			}
		},
		{
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_AGILE"
			}, 
			"weaponSlot":{
				"main":{
					"type":"SYSTEM_EINAT"
				}, 
				"left":{
					"type":"SYSTEM_CL600P"
				}, 
				"right":{
					"type":"SYSTEM_DND_FIX"
				}, 
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"drones":{
				"capacity":1000,
				"initial":1000
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPUFSO"
			},
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			},
			"lidar":{
				"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"capacitor":{
				"capacity":1000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_EIME"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"turbine":{
				"power":1000.0
			}
		},
		{
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_AGILE"
			}, 
			"weaponSlot":{
				"main":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"left":{
					"type":"SYSTEM_CL600P"
				}, 
				"right":{
					"type":"SYSTEM_CL600P"
				}, 
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"drones":{
				"capacity":1000,
				"initial":1000
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPUFSO"
			},
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			},
			"lidar":{
				"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"capacitor":{
				"capacity":1500.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_EIME"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"turbine":{
				"power":1000.0
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":10000.0, 
				"capacity":10000.0
			}, 
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_K69V"
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			},
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_SYNCHRO-L"
				}, 
				"main":{
					"type":"SYSTEM_NANI"
				}, 
				"right":{
					"type":"SYSTEM_SYNCHRO-R"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":10000.0, 
				"capacity":10000.0
			}, 
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_AGILE"
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_BALD"
			}, 
			"reactor":{
				"power":50.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GUIDING"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_OPA"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"main":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"right":{
					"type":"SYSTEM_DND_FIX"
				},
				"leftBack":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"rightback":{
					"type":"SYSTEM_DND_FIX"
				}
			}
		}
]	
