extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["KITSUNE"] = KITSUNE

var KITSUNE = [
	{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			}, 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_RAILTOR"
					}
			}, 
			"reactor":{
				"power":8.0
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0, 
			}, 
			"drones":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":1000.0, 
			}, 
			"turbine":{
				"power":200.0, 
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GRAVIMETRIC"
			},
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			}, 
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			}
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_EINAT"
					}
			}, 
			"reactor":{
				"power":12.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"drones":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"capacitor":{
				"capacity":1500.0, 
			}, 
			"turbine":{
				"power":500.0, 
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_CONE"
			}
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_K44"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_PDMWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0, 
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0, 
			}, 
			"capacitor":{
				"capacity":1000.0, 
			}, 
			"turbine":{
				"power":200.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_KITSUNE"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_MWG"
					}
			}, 
			"reactor":{
				"power":4.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":15000.0, 
				"initial":15000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":100.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			} 
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_BALD"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_DND_FIX"
					}
			}, 
			"reactor":{
				"power":12.0
			}, 
			"ammo":{
				"capacity":5000.0, 
				"initial":5000.0, 
			},
			"drones":{
				"capacity":5000.0, 
				"initial":5000.0, 
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"capacitor":{
				"capacity":1500.0, 
			}, 
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"turbine":{
				"power":500.0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_K69V"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			},
			"lidar":{
				"type":"SYSTEM_LIDAR_OPA"
			},
			"drone":{
				"scanner":"SYSTEM_RD_GUIDING"
			}
		},
		{
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_BALD"
			}, 
			"weaponSlot":{
				"mainLow":{
					"type":"SYSTEM_CL600P"
					}
			}, 
			"reactor":{
				"power":12.0
			}, 
			"ammo":{
				"capacity":5000.0, 
				"initial":5000.0, 
			},
			"drones":{
				"capacity":5000.0, 
				"initial":5000.0, 
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"capacitor":{
				"capacity":1500.0, 
			}, 
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK3"
			},
			"turbine":{
				"power":500.0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"propulsion":{
				"rcs":"SYSTEM_THRUSTER_K69V"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			},
			"lidar":{
				"type":"SYSTEM_LIDAR_DOPPLER"
			},
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			}
		}
	]
