extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs.merge(OCP209)

var OCP209 = {
	"OCP209":[
		{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUSML"
		},
		"drone":{
			"scanner":"SYSTEM_RD_SPECTROMETER"
		},
		"drones":{
			"capacity":10000,
			"initial":10000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP209"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_DFMPD2205",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":30
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"mainRight":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"middleLeft":{
				"type":"SYSTEM_DND_HAUL"
			},
			"middleRight":{
				"type":"SYSTEM_ACL200P"
			}
		}
	},
	{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUSML"
		},
		"drone":{
			"scanner":"SYSTEM_RD_SPECTROMETER"
		},
		"drones":{
			"capacity":10000,
			"initial":10000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP209"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_DFMPD2205",
			"rcs":"SYSTEM_THRUSTER_K44"
		},
		"reactor":{
			"power":40
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"mainRight":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"middleLeft":{
				"type":"SYSTEM_DND_HAUL"
			},
			"middleRight":{
				"type":"SYSTEM_ACL200P"
			}
		}
	}
	]
}
