extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["OCP209"] = OCP209

var OCP209 = [
	{
			"hud":{
				"type":"SYSTEM_HUD_OCP209"
			}, 
			"aux":{
				"power":"SYSTEM_AUX_SMES"
				}, 
			"weaponSlot":{
				"mainLeft":{
					"type":"SYSTEM_SALVAGE_ARM"
				}, 
				"mainRight":{
					"type":"SYSTEM_SALVAGE_ARM"
				}, 
			}, 
			"reactor":{
				"power":16.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0, 
			}, 
			"fuel":{
				"capacity":80000.0, 
				"initial":80000.0, 
			}, 
			"capacitor":{
				"capacity":1000.0, 
			}, 
			"turbine":{
				"power":200.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_DFMPD2205", 
				"rcs":"SYSTEM_THRUSTER_GHET"
			}, 
		},
		{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUSML"
		},
		"drone":{
			"scanner":"SYSTEM_RD_SPECTROMETER"
		},
		"drones":{
			"capacity":10000,
			"initial":10000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP209"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_DFMPD2205",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":30
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"mainRight":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"middleLeft":{
				"type":"SYSTEM_DND_HAUL"
			},
			"middleRight":{
				"type":"SYSTEM_ACL200P"
			}
		}
	},
	{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUSML"
		},
		"drone":{
			"scanner":"SYSTEM_RD_SPECTROMETER"
		},
		"drones":{
			"capacity":10000,
			"initial":10000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP209"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER_HIRES"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_DFMPD2205",
			"rcs":"SYSTEM_THRUSTER_K44"
		},
		"reactor":{
			"power":40
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"mainRight":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"middleLeft":{
				"type":"SYSTEM_DND_HAUL"
			},
			"middleRight":{
				"type":"SYSTEM_ACL200P"
			}
		}
	},
	{
		"ammo":{
			"capacity":20000,
			"initial":20000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_AUX_MPD_MK3"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUFSO"
		},
		"drone":{
			"scanner":"SYSTEM_RD_SPECTROMETER"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":500000,
			"initial":500000
		},
		"hud":{
			"type":"SYSTEM_HUD_OCP209"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_DFMPD2205",
			"rcs":"SYSTEM_THRUSTER_MA350HO"
		},
		"reactor":{
			"power":30
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_SALVAGE_ARM"
			},
			"mainRight":{
				"type":"SYSTEM_DND_HAUL"
			},
			"middleLeft":{
				"type":"SYSTEM_ACL200P"
			},
			"middleRight":{
				"type":"SYSTEM_PDT-R"
			}
		}
	},
	{
		"ammo":{
			"capacity":50000,
			"initial":50000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK4"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GUIDING"
		},
		"drones":{
			"capacity":50000,
			"initial":50000
		},
		"fuel":{
			"capacity":500000,
			"initial":500000
		},
		"hud":{
			"type":"SYSTEM_HUD_PROSPECTOR_BALD"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_OPA"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_DND_FIX"
			},
			"mainRight":{
				"type":"SYSTEM_DND_FIX"
			},
			"middleLeft":{
				"type":"SYSTEM_DND_FIX"
			},
			"middleRight":{
				"type":"SYSTEM_DND_FIX"
			}
		}
	},
	{
		"ammo":{
			"capacity":50000,
			"initial":50000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK4"
		},
		"aux":{
			"power":"SYSTEM_AUX_MPD_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GUIDING"
		},
		"drones":{
			"capacity":50000,
			"initial":50000
		},
		"fuel":{
			"capacity":500000,
			"initial":500000
		},
		"hud":{
			"type":"SYSTEM_HUD_PROSPECTOR_BALD"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_OPA"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"mainLeft":{
				"type":"SYSTEM_NANI"
			},
			"mainRight":{
				"type":"SYSTEM_NANI"
			},
			"middleLeft":{
				"type":"SYSTEM_SYNCHRO-L"
			},
			"middleRight":{
				"type":"SYSTEM_SYNCHRO-L"
			}
		}
	}
]
