extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["PROSPECTOR"].append_array(PROSPECTOR)

var PROSPECTOR = [
	{
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_NMPD", 
				"rcs":"SYSTEM_THRUSTER_MA150HO"
			}, 
			"reactor":{
				"power":40.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_CL150"
				}, 
				"right":{
					"type":"SYSTEM_CL150"
				}, 
			}, 
			"drones":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1000.0
			}, 
			"turbine":{
				"power":500.0
			}
		},
		{
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_NMPD", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"reactor":{
				"power":40.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_CL150"
				}, 
				"right":{
					"type":"SYSTEM_CL150"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_TUG"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"main":{
					"type":"SYSTEM_CL150"
				}
			}, 
			"drones":{
				"capacity":5000.0, 
				"initial":5000.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"turbine":{
				"power":500.0
			},
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_METRIC"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_SPECTROMETER"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			}
		},
		{
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_NMPD", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"reactor":{
				"power":40.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_METRIC"
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_CL150"
				}, 
				"right":{
					"type":"SYSTEM_CL150"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_HAUL"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_FIX"
				},  
				"main":{
					"type":"SYSTEM_SALVAGE_ARM"
				}
			}, 
			"drones":{
				"capacity":5000.0, 
				"initial":5000.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"turbine":{
				"power":500.0
			},
			"drone":{
				"scanner":"SYSTEM_RD_SPECTROMETER"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			}
		},
		{
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_BWMT535", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"reactor":{
				"power":30.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_ACTEMD14"
				}, 
				"right":{
					"type":"SYSTEM_NONE"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_TUG"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"main":{
					"type":"SYSTEM_CL150"
				}
			}, 
			"drones":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"ammo":{
				"capacity":5000.0, 
				"initial":5000.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"turbine":{
				"power":500.0
			},
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_METRIC"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GRAVIMETRIC"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			}
		},
		{
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_K69V"
			}, 
			"reactor":{
				"power":50.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"right":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"main":{
					"type":"SYSTEM_DND_FIX"
				}
			}, 
			"drones":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"turbine":{
				"power":500.0
			},
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_BALD"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GUIDING"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_OPA"
			}
		},
		{
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_K69V"
			}, 
			"reactor":{
				"power":50.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_SYNCHRO-L"
				}, 
				"right":{
					"type":"SYSTEM_SYNCHRO-R"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"main":{
					"type":"SYSTEM_NANI"
				}
			}, 
			"drones":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"turbine":{
				"power":500.0
			},
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			}
		},
		{
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0, 
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K44", 
				"rcs":"SYSTEM_THRUSTER_GHET"
			}, 
			"reactor":{
				"power":50.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"EXSTORAGE-L"
				}, 
				"right":{
					"type":"SYSTEM_CL600P"
				}, 
				"leftDrone":{
					"type":"SYSTEM_DND_HAUL"
				}, 
				"rightDrone":{
					"type":"SYSTEM_DND_TUG"
				}, 
				"main":{
					"type":"SYSTEM_CL600P"
				}
			}, 
			"drones":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":100.0
			}, 
			"turbine":{
				"power":500.0
			},
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR"
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK2"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			}
		}
	]
