# [license]
# 3-Clause BSD NON-AI License
# 
# Copyright 2026 __hev (Benjamin Buckhurst)
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products
# derived from this software without specific prior written permission.
# 
# 4. The source code and the binary form, and any modifications made to them may not be used for the purpose of input data, the training of, or improvment of machine learning algorithms,
# including but not limited to artificial intelligence, natural language processing, or data mining. This condition applies to any derivatives,
# modifications, or updates based on the Software code. Any usage of the source code or the binary form in an AI-training dataset is considered a breach of this License.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# [/license]

extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["TRTL-44"] = TRTL_44

var TRTL_44 = [
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_EIT"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_EXSTORAGE-L"
				}, 
				"rightback":{
					"type":"SYSTEM_EXSTORAGE-R"
				}
			}
		}, 
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K44", 
				"rcs":"SYSTEM_THRUSTER_GHET"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_RADAR"
			},
			"turbine":{
				"power":1500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"rightback":{
					"type":"SYSTEM_PDMWG-R"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_EIT"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_EXSTORAGE-L"
				}, 
				"rightback":{
					"type":"SYSTEM_EXSTORAGE-R"
				}
			}
		}, 
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K44", 
				"rcs":"SYSTEM_THRUSTER_GHET"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_RADAR"
			},
			"turbine":{
				"power":1500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"rightback":{
					"type":"SYSTEM_PDMWG-R"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":80000.0, 
				"initial":80000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K37", 
				"rcs":"SYSTEM_THRUSTER_K37"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_AT225"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_SPECTROMETER"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_HUNK-L"
				}, 
				"right":{
					"type":"SYSTEM_CL150-R"
				},
				"leftBack":{
					"type":"SYSTEM_NONE"
				}, 
				"rightback":{
					"type":"SYSTEM_NONE"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_K37"
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":16.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_NONE"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_ACL200P"
				}, 
				"right":{
					"type":"SYSTEM_SCOOP-R"
				},
				"leftBack":{
					"type":"SYSTEM_EXSTORAGE-L"
				}, 
				"rightback":{
					"type":"SYSTEM_EXSTORAGE-R"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK4"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":10000.0, 
				"capacity":10000.0
			}, 
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_AGILE"
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_PROSPECTOR_BALD"
			}, 
			"reactor":{
				"power":50.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GUIDING"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_OPA"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"right":{
					"type":"SYSTEM_DND_FIX"
				},
				"leftBack":{
					"type":"SYSTEM_DND_FIX"
				}, 
				"rightback":{
					"type":"SYSTEM_DND_FIX"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK1"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":10000.0, 
				"capacity":10000.0
			}, 
			"fuel":{
				"capacity":200000.0, 
				"initial":200000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_K69V"
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":20.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK3"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU_FAB"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_SYNCHRO-L"
				}, 
				"right":{
					"type":"SYSTEM_SYNCHRO-R"
				},
				"leftBack":{
					"type":"SYSTEM_HUNK"
				}, 
				"rightback":{
					"type":"SYSTEM_HUNK"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":10000.0, 
				"capacity":10000.0
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":30.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_GUIDING"
			},
			"aux":{
				"power":"SYSTEM_AUX_MPD_MK2"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPUSML"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_RADAR"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_DND_HAUL"
				}, 
				"right":{
					"type":"SYSTEM_DND_HAUL"
				},
				"leftBack":{
					"type":"SYSTEM_NONE"
				}, 
				"rightback":{
					"type":"SYSTEM_NONE"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1000.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_NMPD", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":12.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_NONE"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_BAFFLES"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_CONE"
			},
			"turbine":{
				"power":200.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_RAILTOR"
				}, 
				"right":{
					"type":"SYSTEM_RAILTOR"
				},
				"leftBack":{
					"type":"SYSTEM_NONE"
				}, 
				"rightback":{
					"type":"SYSTEM_NONE"
				}
			}
		},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK2"
			}, 
			"capacitor":{
				"capacity":1000.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":50000.0, 
				"initial":50000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K37", 
				"rcs":"SYSTEM_THRUSTER_MA350HO"
			}, 
			"ammo":{
				"capacity":10000.0, 
				"initial":10000.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":16.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_NONE"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_CONE"
			},
			"turbine":{
				"power":200.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_ACL200"
				}, 
				"right":{
					"type":"SYSTEM_EXSTORAGE-R"
				},
				"leftBack":{
					"type":"SYSTEM_NONE"
				}, 
				"rightback":{
					"type":"SYSTEM_NONE"
				}
			}
		},	
		{
			"weaponSlot":{
				"right":{
					"type":"SYSTEM_EMD14"
				}, 
				"left":{
					"type":"SYSTEM_NONE"
				}
			}, 
			"reactor":{
				"power":8.0
			}, 
			"ammo":{
				"capacity":1000.0, 
				"initial":1000.0, 
			}, 
			"fuel":{
				"capacity":80000.0, 
				"initial":80000.0, 
			}, 
			"capacitor":{
				"capacity":500.0, 
			}, 
			"turbine":{
				"power":200.0, 
			}, 
			"shielding":{
				"emp":0, 
			}, 
			"cargo":{
				"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_PNTR", 
				"rcs":"SYSTEM_THRUSTER_NDSTR"
			}, 
		},
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_MWG"
				}, 
			"left":{
				"type":"SYSTEM_MWG"
				}
			}, 
		"reactor":{
			"power":8.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":0.0, 
			"initial":0.0
			}, 
		"fuel":{
			"capacity":80000.0, 
			"initial":80000.0, 
			}, 
		"capacitor":{
			"capacity":1000.0, 
			}, 
		"turbine":{
			"power":200.0, 
			},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_PNTR", 
			"rcs":"SYSTEM_THRUSTER_NDSTR"
			}
		}, 
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_CL600P"
				}, 
			"left":{
				"type":"SYSTEM_CL600P"
				},
			"rightBack":{
				"type":"SYSTEM_EXSTORAGE-R"
				},
			"leftBack":{
				"type":"SYSTEM_EXSTORAGE-L"
				}
			}, 
		"reactor":{
			"power":30.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":0.0, 
			"initial":0.0
			}, 
		"fuel":{
			"capacity":80000.0, 
			"initial":80000.0, 
			}, 
		"capacitor":{
			"capacity":1500.0, 
			}, 
		"turbine":{
			"power":500.0, 
			}, 
		"aux":{
			"power":"SYSTEM_AUX_SMES_MK2"
			},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535", 
			"rcs":"SYSTEM_THRUSTER_MA150HO"
			}
		}, 
		{
		"weaponSlot":{
			"right":{
				"type":"SYSTEM_DND_HAUL"
				}, 
			"left":{
				"type":"SYSTEM_PDMWG-L"
				}
			}, 
		"reactor":{
			"power":20.0
			}, 
		"ammo":{
			"capacity":0.0, 
			"initial":0.0, 
			}, 
		"drones":{
			"capacity":5000.0, 
			"initial":5000.0
			}, 
		"fuel":{
			"capacity":50000.0, 
			"initial":50000.0, 
			}, 
		"capacitor":{
			"capacity":1000.0, 
			}, 
		"turbine":{
			"power":200.0, 
			},
		"shielding":{
			"emp":0, 
			}, 
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPUFSO"
			}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535", 
			"rcs":"SYSTEM_THRUSTER_MA150HO"
			}
		},
		{
		"ammo":{
			"capacity":0,
			"initial":0
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK3"
		},
		"aux":{
			"power":"SYSTEM_NONE"
		},
		"capacitor":{
			"capacity":1000
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GRAVIMETRIC"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":50000,
			"initial":50000
		},
		"hud":{
			"type":"SYSTEM_HUD_HAL"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_BWMT535",
			"rcs":"SYSTEM_THRUSTER_NDVTT"
		},
		"reactor":{
			"power":12
		},
		"turbine":{
			"power":200
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_HUNK-L"
			},
			"leftBack":{
				"type":"SYSTEM_HUNK-L"
			},
			"right":{
				"type":"SYSTEM_ACL200P"
			},
			"rightBack":{
				"type":"SYSTEM_DND_HAUL"
			}
		}
	},
		{
		"ammo":{
			"capacity":20000,
			"initial":20000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK4"
		},
		"aux":{
			"power":"SYSTEM_AUX_SMES_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_GUIDING"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_PROSPECTOR_BALD"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_OPA"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_DND_FIX"
			},
			"leftBack":{
				"type":"SYSTEM_DND_FIX"
			},
			"right":{
				"type":"SYSTEM_DND_FIX"
			},
			"rightBack":{
				"type":"SYSTEM_DND_FIX"
			}
		}
	},
		{
		"ammo":{
			"capacity":20000,
			"initial":20000
		},
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK2"
		},
		"aux":{
			"power":"SYSTEM_AUX_MPD_MK3"
		},
		"capacitor":{
			"capacity":1500
		},
		"cargo":{
			"equipment":"SYSTEM_CARGO_MPU_FAB"
		},
		"drone":{
			"scanner":"SYSTEM_RD_STANDARD"
		},
		"drones":{
			"capacity":20000,
			"initial":20000
		},
		"fuel":{
			"capacity":200000,
			"initial":200000
		},
		"hud":{
			"type":"SYSTEM_HUD_HAL"
		},
		"lidar":{
			"type":"SYSTEM_LIDAR_DOPPLER"
		},
		"propulsion":{
			"main":"SYSTEM_MAIN_ENGINE_EIZAP",
			"rcs":"SYSTEM_THRUSTER_K69V"
		},
		"reactor":{
			"power":50
		},
		"turbine":{
			"power":500
		},
		"weaponSlot":{
			"left":{
				"type":"SYSTEM_SYNCHRO-L"
			},
			"leftBack":{
				"type":"SYSTEM_DND_FIX"
			},
			"right":{
				"type":"SYSTEM_SYNCHRO-R"
			},
			"rightBack":{
				"type":"SYSTEM_DND_FIX"
			}
		}
	}
	]
