extends "res://ships/Shipyard.gd"

func _ready():
	usedShipConfigs["TRTL"].append_array(TRTL)

var TRTL = [
	{
		"weaponSlot":{
			"main":{
				"type":"SYSTEM_EMD14"
			}
		}, 
		"ammo":{
			"capacity":1000.0, 
			"initial":1000.0, 
		}, 
		"drones":{
			"initial":0.0, 
			"capacity":0.0, 
		}, 
		"fuel":{
			"capacity":30000.0, 
			"initial":30000.0, 
		}, 
		"capacitor":{
			"capacity":500.0, 
		}, 
		"turbine":{
			"capacity":100.0, 
			"power":100.0, 
		}, 
		"shielding":{
			"emp":0, 
		}, 
		"cargo":{
			"equipment":"SYSTEM_CARGO_STANDARD"
		}, 
		"autopilot":{
			"type":"SYSTEM_AUTOPILOT_MK1"
		}
	},
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_EIZAP", 
				"rcs":"SYSTEM_THRUSTER_EIT"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_DOPPLER_HIRES"
			},
			"turbine":{
				"power":500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"main":{
					"type":"SYSTEM_SALVAGE_ARM"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_EXSTORAGE-L"
				}, 
				"rightback":{
					"type":"SYSTEM_EXSTORAGE-R"
				}
			}
		}, 
		{
			"autopilot":{
				"type":"SYSTEM_AUTOPILOT_MK3"
			}, 
			"capacitor":{
				"capacity":1500.0
			}, 
			"drones":{
				"initial":0.0, 
				"capacity":0.0
			}, 
			"fuel":{
				"capacity":30000.0, 
				"initial":30000.0
			}, 
			"propulsion":{
				"main":"SYSTEM_MAIN_ENGINE_K44", 
				"rcs":"SYSTEM_THRUSTER_GHET"
			}, 
			"ammo":{
				"capacity":0.0, 
				"initial":0.0
			}, 
			"hud":{
				"type":"SYSTEM_HUD_TNTRL"
			}, 
			"reactor":{
				"power":8.0
			}, 
			"drone":{
				"scanner":"SYSTEM_RD_STANDARD"
			},
			"aux":{
				"power":"SYSTEM_AUX_SMES"
			},
			"cargo":{
				"equipment":"SYSTEM_CARGO_MPU"
			}, 
			"lidar":{
				"type": "SYSTEM_LIDAR_RADAR"
			},
			"turbine":{
				"power":1500.0
			}, 
			"weaponSlot":{
				"left":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"main":{
					"type":"SYSTEM_PDMWG"
				}, 
				"right":{
					"type":"SYSTEM_PDMWG-R"
				},
				"leftBack":{
					"type":"SYSTEM_PDMWG-L"
				}, 
				"rightback":{
					"type":"SYSTEM_PDMWG-R"
				}
			}
		}
	]
